### ISSUE TITLE
docker-gpr action fails to run

### ISSUE THREAD

**Issue by warwicklol14** [mattdavis0351/actions#9]
I was doing the GitHub Actions: Publish to GitHub Packages lab when your action failed.

![Annotation 2020-03-18 220051](https://user-images.githubusercontent.com/45288858/76985256-f4ece280-6965-11ea-8345-d726548e437a.jpg)

I checked the url and it says 404 for me too.

**Comment by mattdavis0351** [comment]
Thank you, I'll dig into this right now

**Comment by mattdavis0351** [comment]
@warwicklol14 Thank you so much.  As it turns out a small typo in the releases for this repo caused the issue.  If you go through the course as intended you should see things working with no problems.

![image](https://user-images.githubusercontent.com/38021615/77008002-8e92a080-6922-11ea-8db9-98ab54d6c8f2.png)

I hope you enjoyed the Learning Lab course as you took it!!  There are many more GitHub Actions course that are in the pipeline, so stay tuned to Learning Lab.
